server:
  port: 28001
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  banner:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://192.168.96.136:5432/postgres
    username: postgres
    password: 940802
    driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zte.pojo
  mapper-locations: classpath:com/zte/mapper/*.xml
